Add logic to process two empty files
gregzealley/name-matcher-api pull request #17
Opened 2020-04-06 17:10 UTC by gregzealley

2020-04-07 08:05 UTC, ciaransweet requested changes

2020-04-07 08:05 UTC, ciaransweet commented on src/main/java/com/gregzealley/namematcherapi/controllers/PostController.java
> +                                            HttpServletResponse response) throws IOException, CsvDataTypeMismatchException, CsvRequiredFieldEmptyException {
Some funky tabbing going on?

2020-04-07 08:05 UTC, ciaransweet commented on src/main/java/com/gregzealley/namematcherapi/controllers/PostController.java
> +        StatefulBeanToCsv<MatchResult> writer = new StatefulBeanToCsvBuilder<MatchResult>(response.getWriter())
This is nice!

2020-04-07 08:05 UTC, ciaransweet commented on src/main/java/com/gregzealley/namematcherapi/controllers/PostController.java
> +        writer.write(results);
Assuming you don't need a `using` or a `writer.close()` here?

2020-04-08 14:32 UTC, gregzealley commented on src/main/java/com/gregzealley/namematcherapi/controllers/PostController.java
> +                                            HttpServletResponse response) throws IOException, CsvDataTypeMismatchException, CsvRequiredFieldEmptyException {
Fixed

2020-04-08 14:33 UTC, gregzealley commented on src/main/java/com/gregzealley/namematcherapi/controllers/PostController.java
> +        StatefulBeanToCsv<MatchResult> writer = new StatefulBeanToCsvBuilder<MatchResult>(response.getWriter())
I'll send you the link :wink:

2020-04-08 14:34 UTC, gregzealley commented on src/main/java/com/gregzealley/namematcherapi/controllers/PostController.java
> +        writer.write(results);
Hmmm no such method. We'll assume now :stuck_out_tongue:

2020-04-08 14:48 UTC, merged